# Generated by Django 4.2.20 on 2025-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppsLib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('show', models.BooleanField()),
            ],
        ),
    ]
