# Generated by Django 4.2.20 on 2025-03-15 05:12

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appslib',
            options={'verbose_name': 'Apps library', 'verbose_name_plural': 'Apps library'},
        ),
        migrations.AlterField(
            model_name='appslib',
            name='app_name',
            field=models.CharField(choices=[('core', 'core'), ('financien', 'financien')], max_length=255),
        ),
        migrations.AlterField(
            model_name='appslib',
            name='url',
            field=models.CharField(max_length=255, validators=[core.models.validate_url_endpoints, django.core.validators.RegexValidator(inverse_match=True, message="URL contains invalid characters not in '[A-Za-z0-9_/]'", regex='[^A-Za-z0-9_/]')]),
        ),
    ]
